### ISSUE TITLE
Use react-native-test-app for test apps

### ISSUE THREAD

**Issue by tido64** [microsoft/fluentui-react-native#239]
#### Platform

- [x] iOS
- [x] macOS
- [ ] win32
- [ ] windows
- [x] android
 
#### Describe the feature that you would like added

[`react-native-test-app`](https://github.com/microsoft/react-native-test-app) provides generic test apps for all platforms, i.e. Android, iOS, macOS, and Windows. The idea is that we should only need to take a dev dependency on it, and it will contain all the native parts, include Gradle and Xcode projects, and so on. The package will take care of the native bits, so we can focus on the JS. Upgrading them to support the latest RN should be as simple as bumping the version number in your `package.json`.

The test apps under `apps/` can benefit from using `react-native-test-app` as React Native upgrades will be handled centrally.

#### What component or utility would this be added to

n/a

#### Have you discussed this feature with our team, and if so, who

@FalseLobster, @acoates-ms 

#### Additional context/screenshots

`react-native-test-app` currently doesn't have support for Windows but that shouldn't prevent us from migrating Android, iOS, and macOS.

#### Tasks

- [x] Ensure that RN 0.62 is supported (https://github.com/microsoft/react-native-test-app/issues/110)
- [ ] Migrate Android test app
- [x] Migrate iOS test app (#302)
- [x] Migrate macOS test app (#331)

**Comment by tido64** [comment]
cc @ArazAbishov, @sweggersen

**Comment by FalseLobster** [comment]
@HeyImChris @Saadnajmi FYI

**Comment by Saadnajmi** [comment]
React-Native-macOS isn't on 0.62 yet, which is the main issue from getting us to get it's test app completely stood up. I imagine that blocks you as well @tido64 ?

**Comment by Saadnajmi** [comment]
One more question: Does this mean that each platform would share the dependencies of every other platform, leading to an increased bundle size? AKA, the windows/win32 test app would depend on react-native-macos and vice versa

**Comment by Saadnajmi** [comment]
Also, @HeyImChris , it might be worth contributing to react-native-test-app if we have specific things like xcconfigs we want to add to the test app template, should we choose this route =)

**Comment by tido64** [comment]
@Saadnajmi:
- Regarding macOS and 0.62, it shouldn't be a problem. We are currently on 0.60 internally but I have a PR out with a bump to 0.61. We've made sure that we can support both. It shouldn't be an issue to add 0.62 as well.
- Bundle size: `react-native-test-app` declares dependency on `react-native` and `react-native-macos` in its `package.json`, but that doesn't mean that they'll get bundled with your app. We might over-fetch during `yarn install` but it won't affect your app bundle size.

**Comment by HeyImChris** [comment]
This is really cool. If we do this then we should definitely try using xcconfigs in the apple side of things. Is the idea that this would replace the FabricTester?

**Comment by tido64** [comment]
> Is the idea that this would replace the FabricTester?

Sorry, what's the difference between FabricTester and the test apps in platform folders under `apps/`?

**Comment by FalseLobster** [comment]
ya that's a little overloaded word, so I'll answer Chris myself.  The idea is we'd still load the same bundle but the native bits would be owned by the react-native-test-app npm package.

@tido64 would the binaries come prebuilt? Mostly just curious about this point.

**Comment by tido64** [comment]
@FalseLobster: We ship source code, like how RN does it.

A small update: I've been a bit busy with other things but I've started checking in things to make sure we can support from 0.60 through 0.62 (and future versions). I've created issues on us here: https://github.com/microsoft/react-native-test-app/issues/107, https://github.com/microsoft/react-native-test-app/issues/110.

**Comment by tido64** [comment]
`react-native-test-app` should have proper support for 0.62 as of [0.1.11](https://www.npmjs.com/package/react-native-test-app/v/0.1.11). Do you want us to create an initial PR (migrating only iOS?) so you can evaluate or do you want to do that yourselves?

**Comment by HeyImChris** [comment]
You can move over iOS and I can take a look at that PR. That'd probably be best for us. I can migrate macOS over once it's on 0.62 and ready by mirroring the iOS PR.

**Comment by tido64** [comment]
I have a PR migrating the iOS test app here: #302

Please let me know what you think. Thanks!

**Comment by JasonVMo** [comment]
Closing this one as most of the work has been done here. The remaining work is hooking up android which will be covered by #427
